version: '2'
services:
  rabbitmq:
    container_name: tp_moirai_rabbitmq_container
    image: rabbitmq:3.6.15-alpine
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=carrot
